# clone repo
# Convert MD to MAML

version: 1.0.{build}
branches:
  only:
    - joey-ci

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module -Name platyPS -Repository PSGallery -Force

build_script: 
  - ps: |
      C:/projects/PowerShell-Docs/appveyor.ps1

artifacts:
  - path: C:/projects/powershell-docs/out_cab
